# Generated by Django 5.1.11 on 2025-09-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CountryCapacitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psr_type', models.CharField(max_length=4)),
                ('psr_name', models.CharField(blank=True, default='', max_length=64)),
                ('installed_capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('valid_from_utc', models.DateTimeField()),
                ('year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_country', to='entsoe_api.country')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'year', 'psr_type'], name='entsoe_api__country_efeb0b_idx')],
                'unique_together': {('country', 'psr_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CountryGenerationByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_utc', models.DateTimeField(db_index=True)),
                ('psr_type', models.CharField(max_length=4)),
                ('psr_name', models.CharField(blank=True, default='', max_length=64)),
                ('generation_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('resolution', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_country', to='entsoe_api.country')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'psr_type', 'datetime_utc'], name='entsoe_api__country_2d5744_idx')],
                'unique_together': {('country', 'psr_type', 'datetime_utc')},
            },
        ),
    ]
