# Generated by Django 5.1.11 on 2025-09-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entsoe_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_utc', models.DateTimeField(db_index=True)),
                ('contract_type', models.CharField(choices=[('A01', 'Day-ahead'), ('A07', 'Intraday')], max_length=3)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='EUR', max_length=8)),
                ('unit', models.CharField(blank=True, default='MWH', max_length=8)),
                ('resolution', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices_country', to='entsoe_api.country')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'contract_type', 'datetime_utc'], name='entsoe_api__country_ad7aac_idx')],
                'unique_together': {('country', 'contract_type', 'datetime_utc')},
            },
        ),
    ]
