# Generated by Django 5.1.11 on 2025-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entsoe_api', '0002_countrypricepoint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countrypricepoint',
            index=models.Index(fields=['contract_type', 'datetime_utc'], name='entsoe_api__contrac_d52df4_idx'),
        ),
        migrations.AddIndex(
            model_name='countrypricepoint',
            index=models.Index(fields=['datetime_utc', 'country'], name='entsoe_api__datetim_91e413_idx'),
        ),
    ]
