# Generated by Django 5.1.11 on 2025-10-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entsoe_api', '0003_countrypricepoint_entsoe_api__contrac_d52df4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_utc', models.DateTimeField(db_index=True)),
                ('out_domain_eic', models.CharField(db_index=True, max_length=32)),
                ('in_domain_eic', models.CharField(db_index=True, max_length=32)),
                ('resolution', models.CharField(blank=True, max_length=16, null=True)),
                ('quantity_mw', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['out_domain_eic', 'in_domain_eic', 'datetime_utc'], name='entsoe_api__out_dom_3694d8_idx')],
                'unique_together': {('datetime_utc', 'out_domain_eic', 'in_domain_eic')},
            },
        ),
    ]
