# Generated by Django 5.1.11 on 2025-10-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entsoe_api', '0004_physicalflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalflow',
            name='country_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flows_out', to='entsoe_api.country'),
        ),
        migrations.AddField(
            model_name='physicalflow',
            name='country_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flows_in', to='entsoe_api.country'),
        ),
        migrations.AlterField(
            model_name='physicalflow',
            name='in_domain_eic',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='physicalflow',
            name='out_domain_eic',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='physicalflow',
            index=models.Index(fields=['country_from', 'country_to', 'datetime_utc'], name='entsoe_api__country_76a227_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalflow',
            index=models.Index(fields=['country_from', 'datetime_utc'], name='entsoe_api__country_6ba7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalflow',
            index=models.Index(fields=['country_to', 'datetime_utc'], name='entsoe_api__country_2a2926_idx'),
        ),
    ]
