# Generated by Django 5.2.8 on 2026-02-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entsoe_api", "0006_countrygenerationforecastbytype"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryResGenerationByType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_utc", models.DateTimeField(db_index=True)),
                ("psr_type", models.CharField(max_length=4)),
                ("psr_name", models.CharField(blank=True, default="", max_length=64)),
                (
                    "generation_mw",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=8)),
                ("resolution", models.CharField(blank=True, default="", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_res_country",
                        to="entsoe_api.country",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country", "psr_type", "datetime_utc"],
                        name="resgen_country_psr_ts_idx",
                    )
                ],
                "unique_together": {("country", "psr_type", "datetime_utc")},
            },
        ),
    ]
