# Generated by Django 5.2.11 on 2026-03-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entsoe_api', '0008_countrytiltedirradiancepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryWindSpeedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_utc', models.DateTimeField(db_index=True)),
                ('wind_speed_120m', models.FloatField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wind_speed_country', to='entsoe_api.country')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'datetime_utc'], name='entsoe_api__country_f4f558_idx'), models.Index(fields=['datetime_utc', 'country'], name='entsoe_api__datetim_5f5738_idx')],
                'unique_together': {('country', 'datetime_utc')},
            },
        ),
    ]
