services:
  web:
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      # (same env as above)
    command: sh -c "python manage.py migrate && gunicorn data_api.wsgi:application --bind 0.0.0.0:8000"
    volumes: [ ".:/app" ]
    depends_on: { db: { condition: service_healthy }, redis: { condition: service_healthy } }

  celery_worker:
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      # (same env)
    command: sh -c "python manage.py migrate && celery -A data_api worker -l info"
    volumes: [ ".:/app" ]
    depends_on: { db: { condition: service_healthy }, redis: { condition: service_healthy } }

  celery_beat:
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      # (same env)
    command: celery -A data_api beat -l info
    volumes: [ ".:/app" ]
    depends_on: { db: { condition: service_healthy }, redis: { condition: service_healthy } }

  mqtt:
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      # (same env)
    command: python manage.py mymqtt
    volumes: [ ".:/app" ]
    depends_on: { db: { condition: service_healthy } }
