# entsoe_api/urls.py
from django.urls import path
from .views import (
    AuthTokenRefreshView,
    ActivateAccountView,
    ChartQueryView,
    EnergyAgentChatView,
    CountryCapacityBulkLatestView,
    CountryCapacityLatestView,
    CountryGenerationBulkRangeView,
    CountryGenerationForecastRangeView,
    CountryTiltedIrradianceBulkRangeView,
    CountryTiltedIrradianceRangeView,
    CountryWindSpeedBulkRangeView,
    CountryWindSpeedRangeView,
    CountryGenerationRangeView,
    CountryGenerationResRangeView,
    CountryGenerationYesterdayView,
    CountryPricesBulkRangeView,
    CountryPricesRangeView,
    LoginView,
    MeView,
    PhysicalFlowsLatestView,
    PhysicalFlowsRangeView,
    RegisterView,
    api_root,
)

urlpatterns = [
    path("api/", api_root, name="api-root"),
    path("api/auth/register/", RegisterView.as_view(), name="auth-register"),
    path("api/auth/login/", LoginView.as_view(), name="auth-login"),
    path("api/auth/refresh/", AuthTokenRefreshView.as_view(), name="token-refresh"),
    path("api/auth/activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="auth-activate"),
    path("api/auth/me/", MeView.as_view(), name="auth-me"),
    path("api/chat/", EnergyAgentChatView.as_view(), name="energy-chat"),
    path("api/chart-query/", ChartQueryView.as_view(), name="chart-query"),
    path("api/capacity/latest/", CountryCapacityLatestView.as_view(), name="capacity-latest"),
    path("api/capacity/bulk-latest/", CountryCapacityBulkLatestView.as_view(), name="capacity-bulk-latest"),
    path("api/generation/yesterday/", CountryGenerationYesterdayView.as_view(), name="generation-yesterday"),
    # PRICES (UTC-only, supports period=today|dayahead or start/end)
    path("api/prices/range/", CountryPricesRangeView.as_view(), name="prices-range"),
    path('api/prices/bulk-range/', CountryPricesBulkRangeView.as_view(), name='country-prices-bulk-range'),
    path('api/generation/range/', CountryGenerationRangeView.as_view(), name='generation-range'),
    path('api/generation-res/range/', CountryGenerationResRangeView.as_view(), name='generation-res-range'),
    path('api/generation/bulk-range/', CountryGenerationBulkRangeView.as_view(), name='generation-bulk-range'),
    path('api/generation-forecast/range/', CountryGenerationForecastRangeView.as_view(), name='generation-forecast-range'),
    path('api/generation-irradiance/range/', CountryTiltedIrradianceRangeView.as_view(), name='generation-irradiance-range'),
    path('api/generation-irradiance/bulk-range/', CountryTiltedIrradianceBulkRangeView.as_view(), name='generation-irradiance-bulk-range'),
    path('api/generation-wind-speed/range/', CountryWindSpeedRangeView.as_view(), name='generation-wind-speed-range'),
    path('api/generation-wind-speed/bulk-range/', CountryWindSpeedBulkRangeView.as_view(), name='generation-wind-speed-bulk-range'),
    path("api/flows/range/",  PhysicalFlowsRangeView.as_view(),  name="flows-range"),
    path("api/flows/latest/", PhysicalFlowsLatestView.as_view(), name="flows-latest"),
]


